#!/usr/bin/env bash


declare -gx common_dir
common_dir="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" &&
  pwd -L
)"
source "${common_dir}/-logging-"

function glibc () {(

  # a dispatching function for
  local mode="${1}" ; shift
  case "${mode}" in
    ## 1. detecting the glibc version
    "detect" )
      glibc-detect "${@}"
    ;;
    ## 2. checking a pair of glibc versions for compatibility
    "check" )
      glibc-check "${@}"
    ;;
    ## 3. normalizing the version to 3 components
    "normalize" )
      glibc-normalize "version" "${@}"
    ;;
  esac
)}

function glibc-normalize () {(

  # a dispatching function for normalizing the glibc
  local mode="${1}" ; shift
  case "${mode}" in
    ## 1. normalizing the glibc version to 3 components
    "version" )
      local version="${1}" ; shift
      -logging- "mode=${mode}" "version=${version}"
      IFS="." read -ra components <<< "${version}"
      while [[ "${#components[@]}" -lt "3" ]] ; do
        components+=("0")
      done
      version="$(printf "%s." "${components[@]}")"
      version="${version%"."*}"
      if [[ -n "${version}" ]] ; then
        echo "${version}"
      fi
    ;;
  esac
)}

function glibc-detect () {(

  # a dispatching function for detecting the glibc version
  local mode="${1}" ; shift
  ## modes:
  case "${mode}" in
    ## 1. "env" - unpack the value of a named variable
    ### e.g. 'glibc-detect "env" "c_stdlib_version"'
    ### returns the value of "c_stdlib_version"
    ### it is equivalent to echo "${c_stdlib_version}"
    "env" )
      local named_variable="${1}"
      -logging- "mode=${mode}" "named_variable=${named_variable}"
      echo "${!named_variable}"
    ;;
    ## 2. "required-by" - detect the glibc version required by a library
    ### e.g. 'glibc-detect "required-by" "/path/to/library"'
    ### returns the minimum required version of glibc for the library
    "required-by" )
      glibc-detect "library" "${@}" |
      head --lines=1
    ;;
    ## 3. "system" - detect the version of glibc on the system
    ### e.g. 'glibc-detect "system"'
    ### returns the version of glibc on the system as reported by 'ldd --version'
    "system" )
      -logging- "mode=${mode}"
      ldd --version |
      awk 'NR==1 {print $NF}'
    ;;
    ## 4. "library" - detect all versioned symbols of glibc in a library
    ### e.g. 'glibc-detect "library" "/path/to/library"'
    ### returns all versions of glibc in the symbol table of the library
    "library" )
      local version
      local library="${1}"
      -logging- "mode=${mode}" "library=${library}"
      if [[ -f "${library}" ]] ; then
        readelf -W --syms "${library}" |
        grep "@GLIBC_" |
        sed -n 's/.*@GLIBC_\([0-9.]*\).*/\1/p' |
        sort -Vur | while read -r version ; do
          glibc normalize "${version}"
        done
      fi
    ;;
  esac
)}

function glibc-check () {(

  # a dispatching function for checking glibc compatibility
  local mode="${1}" ; shift
  ## modes:
  case "${mode}" in
    ## 1. "compatible" - check if a detected glibc version is compatible with a provider's version
    ### to accomplish this,
    ### a. normalize the input versions
    ### b. sort the versions in descending order
    ### c. compare the provider's version with the first version in the sorted array
    ### -> if they are equal, the versions are compatible; return 0, and echo "true"
    ### -> if the provider's version is first, it is newer; return 0, and echo "true"
    ### -> if the provider's version is second, it is older; return 1, and echo "false"
    "compatible" )
      local provider detected
      local -a sorted
      provider="$(glibc normalize "${1}")" ; shift
      detected="$(glibc normalize "${1}")" ; shift
      -logging- "mode=${mode}" "provider=${provider}" "detected=${detected}"
      mapfile -t sorted < <(
        printf "%s\n" "${provider}" "${detected}" |
        sort -Vr
      )
      
      if [[ "${provider}" == "${detected}" ]] ; then
        echo "true"
        return 0
      fi
      if [[ "${provider}" == "${sorted[0]}" ]] ; then
        echo "true"
        return 0
      else
        echo "false"
        return 1
      fi
    ;;
    ## 2. "system" - check if the system glibc version is compatible with a library
    ### e.g. 'glibc-check "system" "/path/to/library"'
    ### returns 0 if the system glibc version is compatible with the library
    ### returns 1 if the system glibc version is not compatible with the library
    "system" )
      -logging- "mode=${mode}" "${@}"
      glibc-check "status" \
        "$(glibc-detect "system")" "${@}"
    ;;
    ## 3. "library" - check if a specified glibc version is compatible with a library
    ### for the minimum required glibc symbol in library, compare with the provided version of glibc
    ### e.g. 'glibc-check "library" "2.17" "/path/to/library"'
    ### returns 0 if the library glibc version is compatible with the provided version ("2.17")
    "library" )
      local version
      local glibc_version="${1}" ; shift
      -logging- "mode=${mode}" "glibc_version=${glibc_version}" "${@}"
      while read -r version ; do
        local -a command=(
          "glibc-check" "status"
          "${glibc_version}" "${version}"
        )
        if "${command[@]}" ; then
          return 0
        else
          return 1
        fi
      done < <(glibc-detect "library" "${@}")
    ;;
    "env:library" )
      local named_variable="${1}" ; shift
      -logging- "mode=${mode}" "named_variable=${named_variable}" "${@}"
      glibc-check "library" "${!named_variable}" "${@}"
    ;;
  esac
)}
